name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: mu-jun/eduetech
          stage: main
          yaml: |
            name: hack-edutech-back
            app: python@3.10
            options:
              env:
                - name: DJANGO_SECRET
                  secret: DJANGO_SECRET
                - name: FIREBASE_API_KEY
                  secret: FIREBASE_API_KEY
                - name: FIREBASE_AUTO_DOMAIN
                  secret: FIREBASE_AUTO_DOMAIN
                - name: FIREBASE_STORAGE_BUCKET
                  secret: FIREBASE_STORAGE_BUCKET
                - name: FIREBASE_URL
                  secret: FIREBASE_URL
                - name: OPENAI_ORGANIZATION
                  secret: OPENAI_ORGANIZATION
                - name: OPENAI_API_KEY
                  secret: OPENAI_API_KEY
                - name: SD_AI_API
                  secret: SD_AI_API
              ports: 8000
              start: python3 manage.py runserver 0:8000
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
